# Generated by Django 3.0.6 on 2020-06-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200617_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='levels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Order Confirmed')], default=1),
        ),
    ]
